CREATE TABLE HEE_FLIGHT_SEARCH (
    SEARCH_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- 검색 ID (자동증가)
    AIRLINE_CODE VARCHAR2(10) NOT NULL,             -- 항공사 코드 (KE, OZ, JL 등)
    AIRLINE_NAME VARCHAR2(50) NOT NULL,             -- 항공사 이름 (대한항공, 아시아나 등)
    FLIGHT_NUMBER VARCHAR2(20) NOT NULL,            -- 편명 (KE706, OZ104 등)
    DEPARTURE_AIRPORT VARCHAR2(10) NOT NULL,        -- 출발공항 코드 (ICN, GMP 등)
    ARRIVAL_AIRPORT VARCHAR2(10) NOT NULL,          -- 도착공항 코드 (NRT, BKK 등)
    DEPARTURE_TIME VARCHAR2(50),                    -- 출발시간 (YYYY-MM-DD HH:mm 또는 HH:mm)
    ARRIVAL_TIME VARCHAR2(50),                      -- 도착시간 (YYYY-MM-DD HH:mm 또는 HH:mm)
    DURATION VARCHAR2(30),                          -- 비행시간 (2시간 15분)
    PRICE NUMBER DEFAULT 0,                         -- 가격 (원 단위)
    CURRENCY VARCHAR2(10) DEFAULT 'KRW',            -- 통화 (KRW, USD 등)
    SEAT_CLASS VARCHAR2(20) DEFAULT 'ECONOMY',      -- 좌석 등급 (ECONOMY, BUSINESS, FIRST)
    REMAINING_SEATS VARCHAR2(30) DEFAULT '예약가능',  -- 잔여석 정보 (예약가능, 잔여 3석 등)
    SEARCH_DATE VARCHAR2(20) NOT NULL,              -- 검색한 출발날짜 (YYYY-MM-DD)
    ADULTS NUMBER DEFAULT 1,                        -- 승객 수
    CREATED_DATE DATE DEFAULT SYSDATE               -- 데이터 생성일시 (캐시 관리용)
);